<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" Version="5.0.0-beta-77" />
    <PackageReference Include="LanguageExt.Streaming" Version="5.0.0-beta-77" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="16.0.0-rc.1.40" />
    <PackageReference Include="OneOf" Version="3.0.271" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ParseySharp\ParseySharp.csproj" />
    <ProjectReference Include="..\..\ParseySharp.AspNetCore\ParseySharp.AspNetCore.csproj" />
    <ProjectReference Include="..\..\ParseySharp.HotChocolate\ParseySharp.HotChocolate.csproj" />
    <ProjectReference Include="..\..\ParseySharp.Protobuf.AspNetCore\ParseySharp.Protobuf.AspNetCore.csproj" />
    <ProjectReference Include="..\..\ParseySharp.MessagePack.AspNetCore\ParseySharp.MessagePack.AspNetCore.csproj" />
    <ProjectReference Include="..\..\ParseySharp.Yaml.AspNetCore\ParseySharp.Yaml.AspNetCore.csproj" />
    <ProjectReference Include="..\..\ParseySharp.Avro.AspNetCore\ParseySharp.Avro.AspNetCore.csproj" />
    <ProjectReference Include="..\..\ParseySharp.Json\ParseySharp.Json.csproj" Condition="Exists('..\..\ParseySharp.Json\ParseySharp.Json.csproj')" />
    <ProjectReference Include="..\..\ParseySharp.Swashbuckle\ParseySharp.Swashbuckle.csproj" />
    <ProjectReference Include="..\..\ParseySharp.Refine\ParseySharp.Refine.csproj" />
    <ProjectReference Include="..\..\ParseySharp.Config\ParseySharp.Config.csproj" />
  </ItemGroup>
</Project>
